export const exps_span = {
  timeslice: [
    {
      id: "texqe",
      frame: 1,
      period: "For",
      tMin: -541.0,
      tMax: -535.0,
      longName: "Cambrian\u2013Precambrian boundary",
    },
    {
      id: "texqd",
      frame: 2,
      period: "For",
      tMin: -535.0,
      tMax: -530.0,
      longName: "Early Cambrian (early Terreneuvian)",
    },
    {
      id: "texqc",
      frame: 3,
      period: "For",
      tMin: -530.0,
      tMax: -525.0,
      longName: "Early Cambrian (middle Terreneuvian)",
    },
    {
      id: "texqb",
      frame: 4,
      period: "Sta",
      tMin: -525.0,
      tMax: -520.0,
      longName: "Early Cambrian (late Terreneuvian)",
    },
    {
      id: "texqa",
      frame: 5,
      period: "Sta",
      tMin: -520.0,
      tMax: -515.0,
      longName: "Early\u2013Middle Cambrian boundary)",
    },
    {
      id: "teXPz",
      frame: 6,
      period: "Sta",
      tMin: -515.0,
      tMax: -510.0,
      longName: "Early Middle Cambrian (middle Epoch)",
    },
    {
      id: "teXPy",
      frame: 7,
      period: "Sta",
      tMin: -510.0,
      tMax: -505.0,
      longName: "Early Middle Cambrian (late Epoch 2)",
    },
    {
      id: "teXPx",
      frame: 8,
      period: "Wul",
      tMin: -505.0,
      tMax: -498.8,
      longName: "Late Middle Cambrian (early Epoch 3)",
    },
    {
      id: "teXPw",
      frame: 9,
      period: "Guz",
      tMin: -498.8,
      tMax: -495.5,
      longName: "Late Middle Cambrian (Guzhangian)",
    },
    {
      id: "teXPv",
      frame: 10,
      period: "Pai",
      tMin: -495.5,
      tMax: -491.8,
      longName: "Late Cambrian (Paibian)",
    },
    {
      id: "teXPu",
      frame: 11,
      period: "Jia",
      tMin: -491.8,
      tMax: -485.4,
      longName: "Late Cambrian (Jiangshanian)",
    },
    {
      id: "teXPt",
      frame: 12,
      period: "Sta",
      tMin: -485.4,
      tMax: -481.6,
      longName: "Cambro-Ordovician boundary)",
    },
    {
      id: "teXPs",
      frame: 13,
      period: "Tre",
      tMin: -481.6,
      tMax: -475.0,
      longName: "Early Ordovician (Tremadoc)",
    },
    {
      id: "teXPr",
      frame: 14,
      period: "Flo",
      tMin: -475.0,
      tMax: -470.0,
      longName: "Early Ordovician (late Early Floian)",
    },
    {
      id: "teXPq",
      frame: 15,
      period: "Dap",
      tMin: -470.0,
      tMax: -465.0,
      longName: "Early Ordovician (Floian\u2013Dapingian boundary)",
    },
    {
      id: "teXPp",
      frame: 16,
      period: "Dar",
      tMin: -465.0,
      tMax: -460.0,
      longName: "Middle Ordovician (early Darwillian)",
    },
    {
      id: "teXPo",
      frame: 17,
      period: "Dar",
      tMin: -460.0,
      tMax: -455.7,
      longName: "Middle Ordovician (late Darwillian)",
    },
    {
      id: "teXPn",
      frame: 18,
      period: "San",
      tMin: -455.7,
      tMax: -449.1,
      longName: "Late Ordovician (Sandbian)",
    },
    {
      id: "teXPm",
      frame: 19,
      period: "Kat",
      tMin: -449.1,
      tMax: -444.5,
      longName: "Late Ordovician (Katian)",
    },
    {
      id: "teXPl",
      frame: 20,
      period: "Hir",
      tMin: -444.5,
      tMax: -441.2,
      longName: "Late Ordovician (Hirnantian)",
    },
    {
      id: "teXPk",
      frame: 21,
      period: "Aer",
      tMin: -441.2,
      tMax: -436.0,
      longName: "Early Silurian (early Llandovery)",
    },
    {
      id: "teXPj",
      frame: 22,
      period: "Tel",
      tMin: -436.0,
      tMax: -430.4,
      longName: "Early Silurian (late Llandovery)",
    },
    {
      id: "teXPi",
      frame: 23,
      period: "Hom",
      tMin: -430.4,
      tMax: -425.2,
      longName: "Middle Silurian (Wenlock)",
    },
    {
      id: "teXPh",
      frame: 24,
      period: "Lud",
      tMin: -425.2,
      tMax: -421.1,
      longName: "Late Silurian (Ludlow)",
    },
    {
      id: "teXPg",
      frame: 25,
      period: "Pro",
      tMin: -421.1,
      tMax: -415.0,
      longName: "Late Silurian (Pridoli)",
    },
    {
      id: "teXPf",
      frame: 26,
      period: "Loc",
      tMin: -415.0,
      tMax: -409.2,
      longName: "Early Devonian (Lochkovian)",
    },
    {
      id: "teXPe",
      frame: 27,
      period: "Pra",
      tMin: -409.2,
      tMax: -405.0,
      longName: "Early Devonian (Pragian)",
    },
    {
      id: "teXPd",
      frame: 28,
      period: "Ems",
      tMin: -405.0,
      tMax: -400.0,
      longName: "Early Devonian (early Emsian)",
    },
    {
      id: "teXPc",
      frame: 29,
      period: "Ems",
      tMin: -400.0,
      tMax: -395.0,
      longName: "Early Devonian (middle Emsian)",
    },
    {
      id: "teXPb",
      frame: 30,
      period: "Ems",
      tMin: -395.0,
      tMax: -390.5,
      longName: "Early Devonian (late Emsian)",
    },
    {
      id: "teXPa",
      frame: 31,
      period: "Eif",
      tMin: -390.5,
      tMax: -385.2,
      longName: "Middle Devonian (Eifelian)",
    },
    {
      id: "teXpz",
      frame: 32,
      period: "Giv",
      tMin: -385.2,
      tMax: -380.0,
      longName: "Middle Devonian (Givetian)",
    },
    {
      id: "teXpy",
      frame: 33,
      period: "Fra",
      tMin: -380.0,
      tMax: -375.0,
      longName: "Late Devonian (early Frasnian)",
    },
    {
      id: "teXpx",
      frame: 34,
      period: "Fra",
      tMin: -375.0,
      tMax: -370.0,
      longName: "Late Devonian (late Frasnian)",
    },
    {
      id: "teXpw",
      frame: 35,
      period: "Fam",
      tMin: -370.0,
      tMax: -365.6,
      longName: "Late Devonian (early Famennian)",
    },
    {
      id: "teXpv",
      frame: 36,
      period: "Fam",
      tMin: -365.6,
      tMax: -358.9,
      longName: "Late Devonian (middle Famennian)",
    },
    {
      id: "teXpu",
      frame: 37,
      period: "Fam",
      tMin: -358.9,
      tMax: -354.0,
      longName: "Devonian\u2013Carboniferous boundary",
    },
    {
      id: "teXpt",
      frame: 38,
      period: "Tou",
      tMin: -354.0,
      tMax: -349.0,
      longName: "Early Mississippian (early Tournaisian)",
    },
    {
      id: "teXps",
      frame: 39,
      period: "Tou",
      tMin: -349.0,
      tMax: -344.0,
      longName: "Early Mississippian (late Tournaisian)",
    },
    {
      id: "teXpr",
      frame: 40,
      period: "Vis",
      tMin: -344.0,
      tMax: -338.8,
      longName: "Middle Mississippian (early Visean)",
    },
    {
      id: "teXpq",
      frame: 41,
      period: "Vis",
      tMin: -338.8,
      tMax: -333.0,
      longName: "Middle Mississippian (middle Visean)",
    },
    {
      id: "teXpp",
      frame: 42,
      period: "Vis",
      tMin: -333.0,
      tMax: -330.9,
      longName: "Middle Mississippian (late Visean)",
    },
    {
      id: "teXpo",
      frame: 43,
      period: "Ser",
      tMin: -330.9,
      tMax: -327.0,
      longName: "Late Mississippian (Visean\u2013Serpukhovian boundary)",
    },
    {
      id: "teXpn",
      frame: 44,
      period: "Ser",
      tMin: -327.0,
      tMax: -319.2,
      longName: "Late Mississippian (Serpukhovian)",
    },
    {
      id: "teXpm",
      frame: 45,
      period: "Bas",
      tMin: -319.2,
      tMax: -314.6,
      longName: "Early Pennsylvanian (Bashkirian)",
    },
    {
      id: "teXpl",
      frame: 46,
      period: "Bas",
      tMin: -314.6,
      tMax: -311.1,
      longName:
        "Early\u2013Middle Carboniferous (Bashkirian\u2013Moscovian boundary)",
    },
    {
      id: "teXpk",
      frame: 47,
      period: "Mos",
      tMin: -311.1,
      tMax: -305.4,
      longName: "Middle Pennsylvanian (Moscovian)",
    },
    {
      id: "teXpj",
      frame: 48,
      period: "Kas",
      tMin: -305.4,
      tMax: -301.3,
      longName: "Late Pennsylvanian (Kasimovian)",
    },
    {
      id: "teXpi",
      frame: 49,
      period: "Gzh",
      tMin: -301.3,
      tMax: -297.0,
      longName: "Late Pennsylvanian (Gzhelian)",
    },
    {
      id: "teXph",
      frame: 50,
      period: "Ass",
      tMin: -297.0,
      tMax: -292.6,
      longName: "Early Permian (Asselian)",
    },
    {
      id: "teXpg",
      frame: 51,
      period: "Sak",
      tMin: -292.6,
      tMax: -286.8,
      longName: "Early Permian (Sakmarian)",
    },
    {
      id: "teXpf",
      frame: 52,
      period: "Art",
      tMin: -286.8,
      tMax: -280.0,
      longName: "Early Permian (Artinskian)",
    },
    {
      id: "teXpe",
      frame: 53,
      period: "Kun",
      tMin: -280.0,
      tMax: -275.0,
      longName: "Early Permian (early Kungurian)",
    },
    {
      id: "teXpd",
      frame: 54,
      period: "Kun",
      tMin: -275.0,
      tMax: -268.7,
      longName: "Early Permian (late Kungurian)",
    },
    {
      id: "teXpc",
      frame: 55,
      period: "Wor",
      tMin: -268.7,
      tMax: -265.1,
      longName: "Middle Permian (Roadian and Wordian)",
    },
    {
      id: "teXpb",
      frame: 56,
      period: "Cap",
      tMin: -265.1,
      tMax: -262.5,
      longName: "Middle Permian (Wordian\u2013Capitanian boundary)",
    },
    {
      id: "teXpa",
      frame: 57,
      period: "Cap",
      tMin: -262.5,
      tMax: -256.0,
      longName: "Late Middle Permian (Capitanian)",
    },
    {
      id: "texPz",
      frame: 58,
      period: "Wuc",
      tMin: -256.0,
      tMax: -252.0,
      longName: "Late Permian (Lopingian)",
    },
    {
      id: "texPy",
      frame: 59,
      period: "Ind",
      tMin: -252.0,
      tMax: -244.6,
      longName: "Permo-Triassic boundary",
    },
    {
      id: "texPx",
      frame: 60,
      period: "Ani",
      tMin: -244.6,
      tMax: -239.5,
      longName: "Middle Triassic (Anisian)",
    },
    {
      id: "texPw2",
      frame: 61,
      period: "Lad",
      tMin: -239.5,
      tMax: -233.6,
      longName: "Middle Triassic (Ladinian)",
    },
    {
      id: "texPv1",
      frame: 62,
      period: "Car",
      tMin: -233.6,
      tMax: -232.0,
      longName: "Late Triassic (early Carnian)",
    },
    {
      id: "texPu1",
      frame: 63,
      period: "Car",
      tMin: -232.0,
      tMax: -227.0,
      longName: "Late Triassic (Carnian)",
    },
    {
      id: "texPt1",
      frame: 64,
      period: "Nor",
      tMin: -227.0,
      tMax: -222.4,
      longName: "Late Triassic (Carnian/Norian)",
    },
    {
      id: "texPs1",
      frame: 65,
      period: "Nor",
      tMin: -222.4,
      tMax: -217.8,
      longName: "Late Triassic (early Norian)",
    },
    {
      id: "texPr1",
      frame: 66,
      period: "Nor",
      tMin: -217.8,
      tMax: -213.2,
      longName: "Late Triassic (mid-Norian)",
    },
    {
      id: "texPq1",
      frame: 67,
      period: "Nor",
      tMin: -213.2,
      tMax: -204.9,
      longName: "Late Triassic (late Norian)",
    },
    {
      id: "texPp1",
      frame: 68,
      period: "Rha",
      tMin: -204.9,
      tMax: -201.3,
      longName: "Late Triassic (Rhaetian)",
    },
    {
      id: "texPo1",
      frame: 69,
      period: "Het",
      tMin: -201.3,
      tMax: -196.0,
      longName: "Late Triassic (Rhaetian/Hettangian)",
    },
    {
      id: "texPn1",
      frame: 70,
      period: "Sin",
      tMin: -196.0,
      tMax: -190.8,
      longName: "Early Jurassic (Hettangian and Sinemurian)",
    },
    {
      id: "texPm1",
      frame: 71,
      period: "Sin",
      tMin: -190.8,
      tMax: -186.8,
      longName: "Early Jurassic (Sinemurian/Pliensbachian)",
    },
    {
      id: "texPl1",
      frame: 72,
      period: "Pli",
      tMin: -186.8,
      tMax: -178.4,
      longName: "Early Jurassic (Pliensbachian)",
    },
    {
      id: "texPk1",
      frame: 73,
      period: "Toa",
      tMin: -178.4,
      tMax: -172.2,
      longName: "Early Jurassic (Toarcian)",
    },
    {
      id: "texPj1",
      frame: 74,
      period: "Aal",
      tMin: -172.2,
      tMax: -168.2,
      longName: "Middle Jurassic (Aalenian)",
    },
    {
      id: "texPi1",
      frame: 75,
      period: "Bat",
      tMin: -168.2,
      tMax: -164.8,
      longName: "Middle Jurassic (Bajocian and Bathonian)",
    },
    {
      id: "texPh2",
      frame: 76,
      period: "Cal",
      tMin: -164.8,
      tMax: -160.4,
      longName: "Middle Jurassic (Callovian)",
    },
    {
      id: "texPg1",
      frame: 77,
      period: "Oxf",
      tMin: -160.4,
      tMax: -154.7,
      longName: "Late Jurassic (Oxfordian)",
    },
    {
      id: "texPf1",
      frame: 78,
      period: "Kim",
      tMin: -154.7,
      tMax: -148.6,
      longName: "Late Jurassic (Kimmeridgian)",
    },
    {
      id: "texPe2",
      frame: 79,
      period: "Tit",
      tMin: -148.6,
      tMax: -145.0,
      longName: "Late Jurassic (Tithonian)",
    },
    {
      id: "texPd2",
      frame: 80,
      period: "Tit",
      tMin: -145.0,
      tMax: -142.4,
      longName: "Jurassic\u2013Cretaceous boundary",
    },
    {
      id: "texPc2",
      frame: 81,
      period: "Ber",
      tMin: -142.4,
      tMax: -136.4,
      longName: "Early Cretaceous (Berriasian)",
    },
    {
      id: "texPb2",
      frame: 82,
      period: "Val",
      tMin: -136.4,
      tMax: -131.2,
      longName: "Early Cretaceous (Valanginian)",
    },
    {
      id: "texPa2",
      frame: 83,
      period: "Hau",
      tMin: -131.2,
      tMax: -127.2,
      longName: "Early Cretaceous (Hauterivian)",
    },
    {
      id: "texpz1",
      frame: 84,
      period: "Bar",
      tMin: -127.2,
      tMax: -121.8,
      longName: "Early Cretaceous (Barremian)",
    },
    {
      id: "texpy1",
      frame: 85,
      period: "Apt",
      tMin: -121.8,
      tMax: -115.8,
      longName: "Early Cretaceous (early Aptian)",
    },
    {
      id: "texpx2",
      frame: 86,
      period: "Apt",
      tMin: -115.8,
      tMax: -111.0,
      longName: "Early Cretaceous (late Aptian)",
    },
    {
      id: "texpw2",
      frame: 87,
      period: "Alb",
      tMin: -111.0,
      tMax: -107.0,
      longName: "Early Cretaceous (early Albian)",
    },
    {
      id: "texpv1",
      frame: 88,
      period: "Alb",
      tMin: -107.0,
      tMax: -102.6,
      longName: "Early Cretaceous (middle Albian)",
    },
    {
      id: "texpu1",
      frame: 89,
      period: "Alb",
      tMin: -102.6,
      tMax: -97.2,
      longName: "Early Cretaceous (late Albian)",
    },
    {
      id: "texpt2",
      frame: 90,
      period: "Cen",
      tMin: -97.2,
      tMax: -91.9,
      longName: "Mid-Cretaceous (Cenomanian)",
    },
    {
      id: "texps2",
      frame: 91,
      period: "Tur",
      tMin: -91.9,
      tMax: -86.7,
      longName: "Mid-Cretaceous (Turonian)",
    },
    {
      id: "texpr2",
      frame: 92,
      period: "San",
      tMin: -86.7,
      tMax: -80.8,
      longName: "Late Cretaceous (Santonian and Coniacian)",
    },
    {
      id: "texpq",
      frame: 93,
      period: "Cam",
      tMin: -80.8,
      tMax: -75.0,
      longName: "Late Cretaceous (early Campanian)",
    },
    {
      id: "texpp",
      frame: 94,
      period: "Cam",
      tMin: -75.0,
      tMax: -69.0,
      longName: "Late Cretaceous (late Campanian)",
    },
    {
      id: "texpo1",
      frame: 95,
      period: "Maa",
      tMin: -69.0,
      tMax: -66.0,
      longName: "Late Cretaceous (Maastrichtian)",
    },
    {
      id: "texpn1",
      frame: 96,
      period: "Dan",
      tMin: -66.0,
      tMax: -61.0,
      longName: "Cretaceous\u2013Tertiary boundary (latest Maastrichtian)",
    },
    {
      id: "texpm1",
      frame: 97,
      period: "Sel",
      tMin: -61.0,
      tMax: -56.0,
      longName: "Paleocene (Danian and Thanetian)",
    },
    {
      id: "texpl1",
      frame: 98,
      period: "Tha",
      tMin: -56.0,
      tMax: -51.9,
      longName: "Paleocene\u2013Eocene boundary (PETM)",
    },
    {
      id: "texpk2",
      frame: 99,
      period: "Ypr",
      tMin: -51.9,
      tMax: -44.5,
      longName: "Early Eocene (Ypresian)",
    },
    {
      id: "texpj2",
      frame: 100,
      period: "Lut",
      tMin: -44.5,
      tMax: -39.5,
      longName: "Early Middle Eocene (Lutetian)",
    },
    {
      id: "texpi1",
      frame: 101,
      period: "Bar",
      tMin: -39.5,
      tMax: -35.9,
      longName: "Late Middle Eocene (Bartonian)",
    },
    {
      id: "texph1",
      frame: 102,
      period: "Pri",
      tMin: -35.9,
      tMax: -31.0,
      longName: "Late Eocene (Priabonian)",
    },
    {
      id: "texpg1",
      frame: 103,
      period: "Rup",
      tMin: -31.0,
      tMax: -25.6,
      longName: "Early Oligocene (Rupelian)",
    },
    {
      id: "texpf",
      frame: 104,
      period: "Cha",
      tMin: -25.6,
      tMax: -19.5,
      longName: "Late Oligocene (Chattian)",
    },
    {
      id: "texpe",
      frame: 105,
      period: "Bur",
      tMin: -19.5,
      tMax: -14.9,
      longName: "Early Miocene (Aquitanian and Burdigalian)",
    },
    {
      id: "texpd",
      frame: 106,
      period: "Lan",
      tMin: -14.9,
      tMax: -10.5,
      longName: "Middle Miocene (Langhian)",
    },
    {
      id: "texpc",
      frame: 107,
      period: "Tor",
      tMin: -10.5,
      tMax: -3.1,
      longName: "Middle/Late Miocene (Serravallian and Tortonian)",
    },
    {
      id: "texpb",
      frame: 108,
      period: "Zan",
      tMin: -3.1,
      tMax: 0.0,
      longName: "Late Pliocene (Piacenzian)",
    },
    {
      id: "texpa1",
      frame: 109,
      period: "Pre",
      tMin: 0.0,
      tMax: 0.0,
      longName: "Present day (Holocene)\n",
    },
  ],
} as const
